# .travis.yml for libpointing
#
# Authors: Izzatbek Mukhanov
# Copyright © Inria
# http://libpointing.org/
#
# This software may be used and distributed according to the terms of
# the GNU General Public License version 2 or any later version.
#

language: cpp

os:
    - linux
    - osx

dist: trusty
sudo: required

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: libpointing
    - DOXYFILE: $TRAVIS_BUILD_DIR/building-and-packaging/Doxyfile
    - GH_REPO_REF: github.com/INRIA/libpointing.git
    - secure: "MvGtK11O/ueTSnM4KKdqNHnx7HjR7xgdvBJmUrvyIAjn9ZXftcKq96mv/wU0dF5RLLYQwNpAJSc28+ItpyBB0+h2FFRGdRo12Pov78VDnlMYV07oXDHjja0RtKH+aHKsfqSmB0yxzhEsorOtIDdYJA28147ZmnquzLTFytBc0Id7WwkaR9CsNiAsfQF3BzbknaAZ2CBvAlwFXRmb7Bj7V4adfXqeB57ZWbKIf1tmmZRhEmAK6BIT9O/qQp5266ppxWGsTaNhsl3x0NkPe/fX/9brNTQ2FAaYurZK73GZGBPNwt73lRBbNms8UPXCzzT9f1YS1xBObUto5pwjbUpzqKw33kmwfdSG/vII/6yD1f7ZXrspo+q/W+vneSnaPAU76BLqIzSmstxye6Lg8gr673H6C87PpzZANvx+IlyCfLrohtK5arB8I4hu+M1hkUibMX9qtOSjIyFIdg5yQO7cS8r5i4lCVnPTxEz9iq7aXXkYmnBDXnJ4Ay2JD6JjaBD6C91VCvwyZ99XDFCWn3HY2tYY1qXxLCDZu9pxCRNwYwmevFzJx0WJxYr3HnT2wgBTwmuQ7wu/fmOtXgthGb+ymlScBoisS8a1yIAhm4RI68Byjclzy/6sZLjgevDzCb4LNfB94+SsOdrNZd6oPM9CES3NTYaC10L/hlZw361xlDE="

before_install:
    - |
      if [ $TRAVIS_OS_NAME == linux ] ; then
	  sudo apt-get-repository -y ppa:ubuntu-toolchain-r/ppa ;
          sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ;
          sudo apt-get update -qq ;
      elif [ $TRAVIS_OS_NAME == osx ] ; then
          brew update ;
      fi

install:
    - |
      if [ $TRAVIS_OS_NAME == linux ] ; then
          sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qt5-default ;
          sudo apt-get install -qq libudev-dev ;
          sudo apt-get install -qq xorg-dev ;
          sudo apt-get install -qq freeglut3-dev ;
      elif [ $TRAVIS_OS_NAME == osx ] ; then
          brew ls | grep -wq qt || brew install qt ;
          brew link qt5 --force ;
      fi
    - git config --global user.email "libpointing@inria.fr"
    - git config --global user.name "Travis CI"

before_script:
    - qmake

script:
    - make
    - make check -s

before_deploy:
    - |
      if [ $TRAVIS_OS_NAME == linux ] ; then
          sudo apt-get install -qq doxygen ;
          ./building-and-packaging/linux/create-deb ;
          ./building-and-packaging/update_site ;
      elif [ $TRAVIS_OS_NAME == osx ] ; then
          ./building-and-packaging/mac/update_brew
      fi
    - cd bindings/Java/Jar
    - make all
    - tar -cvf libpointing-java-bindings-$TRAVIS_OS_NAME.tar build libpointing.jar
    - cd ../../..

deploy:
    provider: releases
    api_key: $GITHUB_API_KEY
    file:
        - "building-and-packaging/linux/debian/*.deb"
        - "building-and-packaging/mac/*.tar.gz"
        - "building-and-packaging/mac/Portfile"
        - "bindings/Java/Jar/*.tar"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
        repo: INRIA/libpointing

notifications:
    email: false
