name: macOS

on:
  workflow_run:
    workflows: [Linux]
    types: [completed]

jobs:
  build:

    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt6 and python
      run: |
        brew update
        brew install qt
        brew install python@3.12
        mkdir venv
        python3.12 -m venv venv/
        source venv/bin/activate
        python3.12 -m pip install --upgrade pip
        python3.12 -m pip install setuptools cython

    - name: compile library
      run: |
        cd pointing
        qmake
        make

    - name: compile Python binding
      run: |
        source venv/bin/activate
        cp pointing/libpointing.a bindings/Python/cython/
        cd bindings/Python/cython/
        python3.12 buildcythonlib.py build_ext --inplace
        
    - name: Save the compiled libraries
      uses: actions/upload-artifact@v4
      with:
        path: |
          pointing/libpointing.a
          bindings/Python/cython/libpointing/*.so