name: macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt6
      run: |
        brew update
        brew install qt
    - name: compile
      run: |
        qmake
        make
    - name: Save the compile library
      uses: actions/upload-artifact@v3
      with:
        name: libpointing
        path: pointing/libpointing.a