name: PythonBinding

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
      - uses: actions/checkout@v4
      - name: Install python
        run: |
          apt-get update 
          export DEBIAN_FRONTEND=noninteractive
          apt-get install -y python3.12 python3.12-venv python3-pip cython3
          mkdir venv
          python3.12 -m venv venv/
          . venv/bin/activate
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install setuptools cython

      - name: Download Linux artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: linux.yml
          workflow_conclusion: success
          if_no_artifact_found: fail

      - name: compile Python binding
        run: |
          . venv/bin/activate
          cd bindings/Python/cython/
          ls -la libpointing/
          python3 -m build
          ls -la dist/
